### ISSUE TITLE
Pelajari Django Models

### ISSUE THREAD

**Issue by perymerdeka** [Aawam/Blogging_Django#1]
1. buat apps namanya blog
2. buat models dalam file models.py sesuai dengan tugas yang kemarin
3. register di django admin
4. buat user untuk login dengan nama dev@dev.id pass: dev

## Referensi
* https://www.w3schools.com/django/django_models.php

**Comment by Aawam** [comment]
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/4ff5e107-cd8c-43ec-bcb5-f6589e2d3bb9)

**Comment by Aawam** [comment]
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/94ffc7b2-d06c-47ab-afb0-c8a60ecb1e3c)
mas feri, aku punya problem disini. Ini kenapa ya ?

**Comment by Aawam** [comment]
Mas, aku ada problem disini (Aku baru sampai tugas nomor 2)
Ketika aku coba untuk menampilkan valuesnya, di html tidak terbaca
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/78f23680-dcc3-4540-b794-dbffbb14c389)

beda seperti yang dicontohkan 
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/6b253717-507c-4dc5-9d2c-b05c6f00ddb2)

Padahal step" nya sama.

Aku belum lanjut ke step ke 3, karena stuck disitu.

**Comment by perymerdeka** [comment]
coba drop codenya disini

**Comment by perymerdeka** [comment]
https://docs.djangoproject.com/en/5.0/ref/contrib/admin/
cek disini

**Comment by perymerdeka** [comment]
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Admin_site

**Comment by Aawam** [comment]
Rincian Tugas
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/8bc46e47-da2a-4fb6-824a-cdc3d00b34e2)

Progress Tugas 1
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/61cd6e55-fe20-4e8b-bbfe-ff383b4ef2cf)

Progress Tugas 2
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/a90f48fa-4810-4da0-a5b9-abe4e9f9ada9)

Untuk tugas ke 2, aku masih bingung gimana ngaitkan author dengan user mas.

**Comment by perymerdeka** [comment]
dalam field author, masih ada yang salah karena ga ada relasi antara postinugan dan user

```py
class Blog_Article(models.Model):
    title = models.CharField(max_length=100)
    categories = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    author = models.CharField(max_length=50)
    date_created = models.DateField()
    content = models.TextField(null=True)

    def __str__(self):
        return f"{self.title} by {self.author}"
```

**Comment by Aawam** [comment]
Berarti itu apps di users sama di blog dijadikan satu ya?

**Comment by perymerdeka** [comment]
bukan dijadikan satu tp direlasikan, mirip seperti tag dan categories

**Comment by perymerdeka** [comment]
ga perlu mindah models,

**Comment by Aawam** [comment]
### **better pakai foreignkey atau apa mas ? Untuk author nya**
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/6c05d073-9eca-46a0-9986-ce87cb76f8d1)

### **ini hasil saya**
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/e8d45583-383e-4109-ad6f-4a64daca811d)

### **ini contoh hasilnya**
![image](https://github.com/Aawam/Blogging_Django/assets/150654841/6c0de387-459c-4fa5-bed7-2a421c8c1d00)
