### ISSUE TITLE
Tugas: Buat CRUD di apps Blog pake Function Base View

### ISSUE THREAD

**Issue by perymerdeka** [Aawam/Blogging_Django#3]

**Comment by Aawam** [comment]
Mas, aku ada problem. 

Dibagian Retrieve dari CRUD kan ada 2 jenis, list dan detail. 
Referensi dari [https://www.geeksforgeeks.org/django-crud-create-retrieve-update-delete-function-based-views/?ref=previous_article](url)

Aku dah input datanya di Create tapi di tidak terbaca. Ku cek di admin hasil createnya pun ada. 

ini codenya mas 


```
def list_view(request):

    articles = Blog_Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, "list_view.html", context)
```

**Comment by perymerdeka** [comment]
```py
def list_view(request):

    articles = Blog_Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, "list_view.html", context=context)
```

**Comment by Aawam** [comment]
Uploading 2024-04-20 16-34-35.mp4…

**Comment by Aawam** [comment]
https://github.com/Aawam/Blogging_Django/assets/150654841/b490c0e2-a7e9-43f2-a731-5251bf3cfcb5
